// Code generated by gocode.Generate; DO NOT EDIT.

package sample2

import (
	"fmt"

	"cuelang.org/go/cue"
	"cuelang.org/go/encoding/gocode/gocodec"
	_ "cuelang.org/go/pkg"
)

var cuegenvalUser = cuegenMake("User", &User{})

// Validate validates x.
func (x *User) Validate() error {
	return cuegenCodec.Validate(cuegenvalUser, x)
}

var cuegenCodec, cuegenInstance = func() (*gocodec.Codec, *cue.Instance) {
	var r *cue.Runtime
	r = &cue.Runtime{}
	instances, err := r.Unmarshal(cuegenInstanceData)
	if err != nil {
		panic(err)
	}
	if len(instances) != 1 {
		panic("expected encoding of exactly one instance")
	}
	return gocodec.New(r, nil), instances[0]
}()

// cuegenMake is called in the init phase to initialize CUE values for
// validation functions.
func cuegenMake(name string, x interface{}) cue.Value {
	f, err := cuegenInstance.Value().FieldByName(name, true)
	if err != nil {
		panic(fmt.Errorf("could not find type %q in instance", name))
	}
	v := f.Value
	if x != nil {
		w, err := cuegenCodec.ExtractType(x)
		if err != nil {
			panic(err)
		}
		v = v.Unify(w)
	}
	return v
}

// Data size: 338 bytes.
var cuegenInstanceData = []byte("\x01\x1f\x8b\b\x00\x00\x00\x00\x00\x00\xffD\x8e\xc1j\xdb@\x10\x86gd\x15\xac\xc5\xed\x1b\x14\x16\x1d\x8c\r\xb5\x84\xecC\xb1h\x0f\xa5uO\xa6\x94\u20a1\x14\xb1\x11\x1b\xed&\u04ae\u042e\x0e\xc6\xf1!\x89\xe3\xe4y\xf2\x80\u0660\xd8!s\x9bo\xbe\xf9\xf9\u07fb{\x0f=\xf7\x00\xe8n\x00>\xbb\xeb\x1e\xe2@*c\x99\xca\xf9\x0ffY\u01f1\x87\xfe\x1f\xad-z\x80\xfeof\x05\x0e\x00\xdf\xfd\x94%7\xe8\x0e\x00\xf0\xd1\xddy\x88\x1f\xfe\xfd\xcf[\x1e\x9d\xcb\xf2\xf4y\x00t{\x80\x91\xbb\xed!\xf6\xdf\xf8\x1e\xd0C\xff\x17\xabx\x17\xe4\xbf@\x02\x00\xee\xa9+\x82\x88\xb3BZ\u045eE\xb9\xaeb\xc3T\xad\x8d\x90B\xc7y\xcb'\x86Uu\xc9'\x85\x14\x1b}Q\u01c5\x8e\x8fd\x8a\x88\xfd\xd6\xf0&\xca[\x8e\xee\xb1f\xf9%+8=]\t\x91U\xad\x1bKCc\x1b\xa9\n\x13\x12\xf2\xd7\xf0&\xa5\xeb,\xf9\xba%A&6\xb5\xe0*\xcbu\xablJOV\xf4\xbd[G\xeb,\x89V\x8b\xe5'\x1aN\xc21\x1d\xd2-\t\x82)\tv$\xc8J\xae\n+RZr\xf5\xaau\xc6(\x99\xd2+\x9a\xcc\xc6$X-\x96)\xed\xe6\x98I\x82o\x05?\x82V*K\x87\xf4\xcb|>';\x02\xf0\x1c\x00\x00\xff\xffa\x81o\x05\x8d\x01\x00\x00")
